[package]
name = "hyperloglog"
version = "0.0.13"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Hyperloglog implementation in Rust"
license = "ISC"
homepage = "https://github.com/jedisct1/rust-hyperloglog"
repository = "https://github.com/jedisct1/rust-hyperloglog"
edition = "2018"

[lib]
name = "hyperloglog"
path = "src/hyperloglog/lib.rs"

[dependencies]
bytecount = { version = "0.6", optional = true }
rand = { version = "0.7", optional = true }
siphasher = { version = "0.3", optional = true }
serde_json = { version = "1.0", optional = true }

[dependencies.serde]
version = "1.0"
features = ["derive"]

[features]
with_serde = ["serde/std", "serde_json"]
std = ["bytecount", "rand", "siphasher"]
default = ["std"]
